app/forms/add_comment.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from flask_wtf.file import FileField, FileAllowed

from wtforms.validators import DataRequired, Length
    
class AddCommentForm(FlaskForm):
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Create Post')

app/forms/create_post.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from flask_wtf.file import FileField, FileAllowed

from wtforms.validators import DataRequired, Length
    
class CreatePostForm(FlaskForm):
    title = StringField('Title:', validators=[DataRequired(), Length(min=8, max=64)], render_kw={"placeholder": "Input your thoughts there..."})
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Create Post')

app/forms/invite_friend.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length
    
class InviteFriendForm(FlaskForm):
    username = StringField('Input user\'s name', validators=[DataRequired(), Length(min=4)])
    submit = SubmitField('Send invite')

app/forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length
    
class LoginForm(FlaskForm):
    username_or_email = StringField('Username or Email', validators=[DataRequired(), Length(min=4)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=8)])
    remember = BooleanField('Remember me')
    submit = SubmitField('Login')

app/forms/messenger.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, EmailField, BooleanField
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms.validators import DataRequired

class MessengerForm(FlaskForm):
    content = StringField('Write a message...', validators=[DataRequired()])

app/routes/posts.py
from flask import Blueprint, render_template, redirect, url_for, flash, current_app, jsonify, request, session
from flask_login import login_user, login_required, logout_user, current_user
from app.forms import CreatePostForm, AddCommentForm
from app.models import User, Post, Comment, Like, UserVerification, Report
from app.extensions import db, login_manager
from app.utils import to_sentence_case, is_email_or_username, generate_random_text, Symbols, check_verify_status, require_not_banned, fix_img_src_paths
from datetime import datetime
from werkzeug.utils import secure_filename
import os, unicodedata, re, random, uuid

posts_bp = Blueprint('posts', __name__, url_prefix='/posts')

@posts_bp.route('/create', methods=['GET'])
@login_required
@require_not_banned
def create_post_form():
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    params = {
        "form": CreatePostForm()
    }
    
    return render_template('create_post.html', show_title=True, header="Create Post", **params)

@posts_bp.route('/create', methods=['POST'])
@login_required
@require_not_banned
def create_post_submit():
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    form = CreatePostForm()
    
    title = Symbols.clean_title(form.title.data)
    slug = Symbols.slug()
    content = fix_img_src_paths(form.content.data)
    
    post = Post(author_id=current_user.id, title=title, slug=slug, content=content, created_at=datetime.now())
    if post and content:
        db.session.add(post)
        db.session.commit()
        
        flash("Post has been successfully created!", 'success')
        
        post.send_news()
    else:
        flash("Post cannot be created", 'error')
        
    return redirect(url_for('profile.profile'))
    
# @posts_bp.route('/upload-image', methods=['POST'])
# @login_required
# @require_not_banned
# def upload_image():
#     file = request.files.get('file')
#     if not file:
#         return jsonify({'error': 'No file uploaded'}), 400

#     filename = secure_filename(file.filename)
#     ext = os.path.splitext(filename)[1].lower()

#     if ext not in ['.jpg', '.jpeg', '.png', '.gif', '.webp']:
#         flash("Invalid file format", 'error')
#         return redirect(url_for('create_post'))

#     unique_name = f"{uuid.uuid4().hex}{ext}"
#     save_path = f'app/static/uploads/{unique_name}'
#     file.save(save_path)

#     file_url = url_for('static', filename=f'uploads/{unique_name}', _external=False)
    return jsonify({'location': file_url})

@posts_bp.route('/add_comment', methods=['GET'])
@login_required
@require_not_banned
def add_comment_form():
    post_id = request.args.get('post_id')
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    form = AddCommentForm()
    
    return render_template('add_comment.html', show_title=False, post_id=post_id, form=form, header="Add Comment")

@posts_bp.route('/add_comment', methods=['POST'])
@login_required
@require_not_banned
def add_comment_submit():
    post_id = int(request.args.get('post_id'))
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    form = AddCommentForm()
    
    if form.validate_on_submit():
        params = {
            "author_id": current_user.id,
            "post_id": int(request.args.get('post_id')),
            "content": request.form.get('content'),
            "created_at": datetime.now()
        }
        
        new_comment = Comment(**params)
        db.session.add(new_comment)
        db.session.commit()
        
        flash("Comment successfully created.", 'success')
    else:
        flash("Something went wrong while proceeding your comment, try again later.", 'error')
    
    author_id = db.session.get(Post, post_id).author_id
    if author_id == current_user.id:
        return redirect(url_for('profile.profile'))
    return redirect(url_for('friends.friends_profile', friend_id=author_id))

@posts_bp.route('/like/<int:id>')
@login_required
def like_post_form(id):
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    post = db.session.get(Post, id)
    if post:
        like = db.session.query(Like).filter_by(user_id=current_user.id, post_id=id).first()
        
        if like:
            db.session.delete(like)
        else:
            new_like = Like(user_id=current_user.id, post_id=id, created_at=datetime.now())
            
            db.session.add(new_like)
        db.session.commit()
        
        if current_user.id == post.author.id:
            return redirect(url_for('profile.profile'))
        return redirect(url_for('friends.friends_profile', friend_id=post.author.id))
    
@posts_bp.route('/delete/<int:id>')
@login_required
@require_not_banned
def delete_post_form(id):
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    post = db.session.get(Post, id)
    if post:
        if post.author_id != current_user.id:
            is_own = False
            flash("This is not your post!", 'error')
        else:
            is_own = True
            
            post.mark_as_deleted()
            db.session.commit()
            
            flash("Post has been successfully deleted!", 'success')
            
            post.delete_news()

        if not is_own:
            return redirect(url_for('friends.friends_profile', friend_id=post.author.id))
    else:
        flash("Post has not found.", 'error')
    return redirect(url_for('profile.profile'))

@posts_bp.route('/return/<int:id>')
@login_required
@require_not_banned
def return_post_form(id):
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    post = db.session.get(Post, id)
    if post:
        if post.author_id != current_user.id:
            is_own = False
            flash("This is not your post!", 'error')
        else:
            is_own = True
            
            post.mark_as_returned()
            db.session.commit()
            
            flash("Post has been successfully returned!", 'success')
            
            post.send_news(return_news=True)
        if not is_own:
            return redirect(url_for('friends.friends_profile', friend_id=post.author.id))
    else:
        flash("Post has not found.", 'error')
    return redirect(url_for('profile.profile'))

@posts_bp.route('/repost/<int:id>')
@login_required
@require_not_banned
def repost_form(id):
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    post = db.session.get(Post, id)
    if post:
        if post.author_id == current_user.id:
            if post.reference:
                flash("You can\'t repost your own repost!", 'error')
            else:
                flash("You can\'t repost your own post!", 'error')
        else:
            prev = db.session.query(Post).filter_by(author_id=current_user.id, reference=id, is_deleted=False).first()
            if prev:
                flash("Previous repost of this post deleted.", 'warning')
                prev.mark_as_deleted()
                
            new_post = Post(content=post.content, created_at=post.created_at, author_id=current_user.id, title=post.title, slug=Symbols.slug())
            new_post.tag_as_reposted(id=post.id)

            db.session.add(new_post)
            db.session.flush()

            if prev:
                comments = db.session.query(Comment).filter_by(post_id=prev.id).all()
                for comment in comments:
                    comment.post_id = new_post.id
                    comment.is_migrated = True
            
            db.session.commit()
            
            flash("Post has been successfully reposted.", 'success')
    else:
        flash("Post has not found.", 'error')
    return redirect(url_for('profile.profile'))

@posts_bp.route('/edit/<int:id>', methods=['GET'])
@login_required
@require_not_banned
def edit_post_form(id):
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    post = db.session.get(Post, id)
    if post and post.author_id == current_user.id and not post.is_reposted:
        params = {
            "form": CreatePostForm(),
            "title": post.title,
            "content": post.content
        }
        
        return render_template('create_post.html', id=id, show_title=True, header="Edit Post", type="edit", action=url_for('posts.edit_post', id=id), **params)
    flash("This post cannot be edited!", 'error')
    return redirect(url_for('profile.profile'))

@posts_bp.route('/edit/<int:id>', methods=['POST'])
@login_required
@require_not_banned
def edit_post(id):
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    post = db.session.get(Post, id)
    if post and post.author_id == current_user.id and not post.is_reposted:
        form = CreatePostForm()
        
        title = Symbols.clean_title(form.title.data)
        content = fix_img_src_paths(form.content.data)
    
        if (content != post.content or title != post.title) and content and title:
            post.content = content
            post.title = title
            
            post.is_edited = True
            post.edited_at = datetime.now()
            db.session.commit()
            
            flash("Post has been successfully edited!", 'success')
        else:
            flash("Wrong content or title!", 'error')
    else:
        flash("This post cannot be edited!", 'error')
    return redirect(url_for('profile.profile'))

@posts_bp.route('/edit/comment/<int:id>', methods=['GET'])
@login_required
@require_not_banned
def edit_comment_form(id):
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    comment = db.session.get(Comment, id)

app/routes/profile.py
from flask import Blueprint, render_template, redirect, url_for, flash, current_app, jsonify, request, session
from flask_login import login_user, login_required, logout_user, current_user
from app.forms import InviteFriendForm, UpdateForm, MessengerForm
from app.models import User, Friendship, Message, NewsItem
from app.extensions import db, login_manager
from app.utils import to_sentence_case, is_email_or_username, flatten, check_verify_status, require_not_banned, bool_conv, upload_to_supabase, delete_from_supabase
from sqlalchemy import or_, and_
from datetime import datetime
from wtforms.validators import DataRequired
from dotenv import load_dotenv
import os, uuid, requests

profile_bp = Blueprint('profile', __name__, url_prefix='/profile')

@profile_bp.route('/', methods=['GET'])
@login_required
def profile():
    friend_list = db.session.query(User, Friendship.is_accepted, Friendship.user2_id).filter(or_(and_(Friendship.user2_id == current_user.id, User.id == Friendship.user1_id), and_(Friendship.user1_id == current_user.id, User.id == Friendship.user2_id))).all()
    session.setdefault('show_hidden_posts', True)
    
    updated_friend_list = []
    friend_invites = []
    for friend in friend_list:
        updated_friend_list.append(dict(friend[0].to_dict(), is_accepted=friend[1]))
        if not updated_friend_list[-1]['is_accepted'] and friend[2] == current_user.id:
            friend_invites.append(updated_friend_list[-1])
            
    params = {
        "friends": updated_friend_list,
        "invites": friend_invites
    }
    
    data = current_user.to_dict()
    user_posts = current_user.get_posts(get_comments=True, get_deleted_posts=True)
    visible_posts = [post for post in user_posts if (post['is_deleted'] and session['show_hidden_posts']) or not post['is_deleted']]
    
    return render_template('profile.html', supabase_url=os.environ.get("SUPABASE_URL"), prefix="Your", self_profile=True, visible_posts=visible_posts, user_posts=user_posts, **data, **params, body_class='profile', current_user=current_user, show_hidden_posts=session['show_hidden_posts'])

@profile_bp.route('/hidden_posts_statement/<show_hidden_posts>')
@login_required
def hidden_posts_statement(show_hidden_posts):
    show_hidden_posts = bool_conv(show_hidden_posts)
    session['show_hidden_posts'] = show_hidden_posts
    
    return redirect(url_for('profile.profile'))

@profile_bp.route('/update/<field>', methods=['GET'])
@login_required
@require_not_banned
def update_form(field):
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    field_to_update = ""
    form = UpdateForm()
    match field:
        case "username":
            field_to_update = 'username'
        case "picture":
            field_to_update = 'picture'
    
    return render_template('update.html', field=field_to_update, form=form)
        
@profile_bp.route('/update/<field>', methods=['POST'])
@login_required
@require_not_banned
def update_submit(field):
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    form = UpdateForm(field=field)
    if form.validate_on_submit():
        if current_user.check_password(form.old_password.data):
            match field:
                case "username":
                    username = form.username.data
                    if db.session.query(User).filter_by(username=username).first():
                        flash("Username already exists", 'error')
                        return redirect(url_for('profile.update_form', field=field))
                    current_user.username = username
                case "picture":
                    filename = uuid.uuid4().hex[:16] + os.path.splitext(form.picture.data.filename)[1]
                    if current_user.picture != "default.png":
                        delete_from_supabase(bucket_name="avatars", file_path=f"users/{current_user.picture}")
                    upload_to_supabase(form.picture.data, bucket_name="avatars", another_name=filename)
                    current_user.picture = filename
                case default:
                    flash("Can\'t find this field", 'error')
                    return redirect(url_for('profile'))
            db.session.commit()
            flash("Successfully updated", 'success')
            return redirect(url_for('profile.profile'))
        flash("Wrong password", 'error')
        return redirect(url_for('profile.update_form', field=field))
    errors = form.errors
    for error_keys in errors:
        for error in errors[error_keys]:
            flash(f"\'{error_keys}\': {error}", 'error')
    return redirect(url_for('profile.update_form', field=field))

@profile_bp.route('/hide_news_item/<int:id>')
@login_required
def hide_news_item(id):
    verify_status = check_verify_status()
    if verify_status:
        return verify_status
    
    news_item = db.session.get(NewsItem, id)
    
    if news_item and news_item.recipient_id == current_user.id:
        db.session.delete(news_item)
        db.session.commit()
        
        flash("Successfully deleted", 'success')
    else:
        flash("Can\'t delete this news item", 'error')

    return redirect(url_for('profile.profile'))

@profile_bp.route('/upload_image', methods=['POST'])
def upload_image():
    file = request.files["file"]
    bucket_name = request.args.get("bucket_name")

    result = upload_to_supabase(file, bucket_name)

    if result["success"]:
        return jsonify({"location": result["url"]}), 200
    else:
        return jsonify({"error": result["error"]}), 400

@profile_bp.route('/get_profile_picture_url')
def get_profile_picture_url():
    url = f"{os.environ.get('SUPABASE_URL')}/storage/v1/object/public/avatars/users/{current_user.picture}"
    return jsonify({"url": url})

app/templates/_editor.html
{# templates/_editor.html #}
<div class="create-post block">
    <h2>{{ header if header else "Editor"}}</h2>

    {% include '_flash.html' %}
    
    {% if show_title %}
    <div class="field create-post-field">
        {% set title = title if type == "edit" else "" %}
        {{ form.title(placeholder=form.title.label.text, value=title) }}
    </div>
    {% endif %}

    <div class="editor">
        <script>
            const data = {{ content | default('') | tojson }};

            tinymce.init({
                selector: '#editor',
                plugins: 'link image code lists',
                toolbar: 'undo redo | bold italic | alignleft aligncenter alignright | code',
                images_upload_url: '{{ url_for("profile.upload_image", bucket_name="posts") }}',
                automatic_uploads: true,
                images_upload_credentials: true,

                init_instance_callback: function (editor) {
                    editor.setContent(data);
                }
            });
        </script>
        {{ form.content(id='editor') }}
    </div>

    <div class="field">
        {{ form.submit(value=header if header else "Editor") }}
    </div>
    
    <div style="margin-top:0.6rem; display:flex; justify-content:space-between">
        
        <a href="{{ history[-2]}}">Return back</a>
        <a href="{{ url_for('profile.profile') }}">Return to profile</a>
    </div>
</div>

app/templates/_flash.html
{# templates/_flash.html #}
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="alerts">
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
        <img src="{{ url_for('static', filename='images/status/' + category + '.webp') }}" style="width:20px;height:20px;margin-right:4px">
        <div class="alert-text">{{ message }}</div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

app/templates/_friend.html
{% if friend["is_accepted"] %}
<a href="{{ href }}" style="all: unset; cursor: pointer;">
    <div class="friend">
        <div class="friend-image">
            <img src="{{ supabase_url }}/storage/v1/object/public/avatars/users/{{ friend['picture'] }}" alt="">
        </div>
        <div class="friend-data">
            <div class="small-text username">
                {{ friend['username'] }}
            </div>
            <div class="small-text email">
                {{ friend['email'] }}
            </div>
        </div>
    </div>
</a>
{% endif %}

app/templates/_messenger.html
<div class="messenger block" id="messenger">
    <div class="content" style="box-sizing:border-box">
        {% for message in messages %}
        <div class="message" data-message-id="{{ message['id'] }}" data-message-is-forwarded="{{ message['is_forwarded'] }}" data-sender-id="{{ message['sender'] }}">
            <div>
                <img class="profile-picture" src="{{ supabase_url }}/storage/v1/object/public/avatars/users/{{ message['sender_picture'] }}" alt="">
                
            </div>
            <div>
                {% if message['is_forwarded'] %}
                <div class="small-text" style="font-style: italic">
                    <div class="is-forwarded" title="Forwarded at {{ message['forwarded_at'] }}">Forwarded from <img class='forwarded-picture' src="{{ supabase_url }}/storage/v1/object/public/avatars/users/{{ message['forwarded_message_author_picture'] }}" alt=""> {{ message['forwarded_message_author'] }}</div>
                </div>
                {% endif %}
                <div class="small-text">
                    {{ message['sender_username'] }} • {{ message['sended_at'] }} {% if message['is_edited'] %} • <img class='edited-picture' src="{{ url_for('static', filename='images/buttons/edit.png')}}" title="Edited {{ message['edited_at_shorten'] }} ago [{{ message['edited_at'] }}]"> {% endif %}
                </div>
                <div>
                    {{ message['content'] }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <form method="POST" action="{{ url_for('messages.send_message', friend_id=friend_id) }}">
        <div class="panel">
            <div class="send-message">
                {{ form.content(placeholder=form.content.label.text, autocomplete='off', autofocus=True) }}
            </div>
            <div class="send">
                <button>
                    <img src="{{ url_for('static', filename='images/buttons/send.png')}}" alt="">
                </button>
            </div>
        </div>
    </form>
</div>

<div class="context-menu" id="global-context-menu">
    <div class="menu-item" id="edit" onclick="handleMenuAction('edit')">Edit</div>
    <div class="menu-item" id="forward" onclick="handleMenuAction('forward')">Forward</div>
    <div class="menu-item" id="remove" onclick="handleMenuAction('remove')">Remove</div>
</div>

<script>
    window.onload = function() {
        const content = document.querySelector('.messenger .content');
        if (content) {
            content.scrollTop = content.scrollHeight;
        }
    };
</script>

<script>
    let currentMessageId = null;
    const friendId = {{ friend_id | tojson }};
    const currentUserId = {{ id | tojson }};

    document.querySelectorAll('.message').forEach(msg => {
        msg.addEventListener('contextmenu', function(e) {
            e.preventDefault();

            const menu = document.getElementById('global-context-menu');
            const messageSenderId = this.dataset.senderId; 
            const messageIsForwarded = this.dataset.messageIsForwarded
            
            const editMenuItem = document.getElementById('edit');
            const removeMenuItem = document.getElementById('remove');
            const forwardMenuItem = document.getElementById('forward');

            editMenuItem.style.display = 'none';
            removeMenuItem.style.display = 'none';
            forwardMenuItem.style.display = 'none';

            if (messageSenderId && parseInt(messageSenderId) === currentUserId) {
                editMenuItem.style.display = 'block';
                removeMenuItem.style.display = 'block';
                forwardMenuItem.style.display = 'block';
            } else if (messageSenderId && parseInt(messageSenderId) === friendId) {
                forwardMenuItem.style.display = 'block';
            }

            if (messageIsForwarded === 'True') {
                editMenuItem.style.display = 'none';
            }

            menu.style.display = 'block';
            menu.style.left = e.pageX + 'px';
            menu.style.top = e.pageY + 'px';

            currentMessageId = msg.dataset.messageId;
        });
    });

    document.addEventListener('click', function(event) {
        const menu = document.getElementById('global-context-menu');
        if (!menu.contains(event.target)) {
            menu.style.display = 'none';
        }
    });

    function handleMenuAction(action) {
        if (currentMessageId) {
            const url = `/messages/${action}/${currentMessageId}?friend_id=${friendId}`;
            window.location.href = url;
        }
    }

    window.onload = function() {
        const content = document.querySelector('.messenger .content');
        if (content) {
            content.scrollTop = content.scrollHeight;
        }
    };
</script>

<script>
    let lastMessageId = Math.max(...Array.from(document.querySelectorAll('.message'))
        .map(m => parseInt(m.dataset.messageId || 0)));

    function fetchNewMessages() {
        fetch(`/messages/live?friend_id=${friendId}&after_id=${lastMessageId}`)
            .then(response => response.json())
            .then(messages => {
                const box = document.querySelector('.messenger .content');
                messages.forEach(msg => {
                    const messageDiv = document.createElement('div');
                    messageDiv.classList.add('message');
                    messageDiv.dataset.messageId = msg.id;
                    messageDiv.dataset.messageIsForwarded = msg.is_forwarded;
                    messageDiv.dataset.senderId = msg.sender;

                    messageDiv.innerHTML = `
                        <div>
                            <img class="profile-picture" src="https://wtyxtyyiuelqcfsdyixh.supabase.co/storage/v1/object/public/avatars/users/${msg.sender_picture}" alt="">
                        </div>
                        <div>
                            ${msg.is_forwarded ? `
                                <div class="small-text" style="font-style: italic">
                                    <div class="is-forwarded" title="Forwarded at ${msg.forwarded_at}">Forwarded from 
                                    <img class='forwarded-picture' src="https://wtyxtyyiuelqcfsdyixh.supabase.co/storage/v1/object/public/avatars/users/${msg.forwarded_message_author_picture}" alt=""> ${msg.forwarded_message_author}</div>
                                </div>` : ''}
                            <div class="small-text">
                                ${msg.sender_username} • ${msg.sended_at} ${msg.is_edited ? ` • <img class='edited-picture' src="/static/images/buttons/edit.png" title="Edited ${msg.edited_at_shorten} ago [${msg.edited_at}]">` : ''}
                            </div>
                            <div>${msg.content}</div>
                        </div>
                    `;

                    box.appendChild(messageDiv);
                    lastMessageId = Math.max(lastMessageId, msg.id);
                    box.scrollTop = box.scrollHeight;
                });
            });
    }

    setInterval(fetchNewMessages, 3000);
</script>

app/templates/_submit.html
{# templates/_submit.html #}
<div class="button-container">
    {% if type == 'button' %}
    <button type="submit" class="button" href="{{ href }}">
    {% include '_submit_inner.html' %}
    </button>
    {% else %}
    <a type="submit" class="button" href="{{ href }}">
    {% include '_submit_inner.html' %}
    </a>
    {% endif %}
</div>

app/templates/_submit_inner.html
{# templates/_submit_inner.html #}
<div class="button__content">
    <span class="button__text">
        {{ button_text }}
    </span>

    <div class="button__reflection-1"></div>
    <div class="button__reflection-2"></div>
</div>

<img src="{{ url_for('static', filename='images/buttons/star.png') }}" alt="" class="button__star-1">
<img src="{{ url_for('static', filename='images/buttons/star.png') }}" alt="" class="button__star-2">
<img src="{{ url_for('static', filename='images/buttons/circle.png') }}" alt="" class="button__circle-1">
<img src="{{ url_for('static', filename='images/buttons/circle.png') }}" alt="" class="button__circle-2">
<img src="{{ url_for('static', filename='images/buttons/diamond.png') }}" alt="" class="button__diamond">
<img src="{{ url_for('static', filename='images/buttons/triangle.png') }}" alt="" class="button__triangle">

<div class="button__shadow"></div>

app/templates/add_comment.html
{% extends 'base.html' %}

{% block title %}Add Comment - SimpleBook{% endblock %}

{% block content %}
<script src="https://cdn.tiny.cloud/1/6yijs7mcax5p8ozmvlm1udf7klkrdqkvp1d03hoqtyjv52nr/tinymce/6/tinymce.min.js"></script>
<form method="POST" action="{{ url_for('posts.add_comment_submit', post_id=post_id) }}" novalidate>
    {{ form.hidden_tag() }}
    {% include '_editor.html' %}
</form>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/button.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" href="{{ url_for('static', filename='images/buttons/logo.png') }}" type="image/png">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Nunito:ital,wght@0,200..1000;1,200..1000&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
    <title>{% block title %}SimpleBook{% endblock %}</title>
    <style>
        body {
            background-image: url("{{ url_for('static', filename='images/bg.jpg') }}");
        }
    </style>
</head>
<body class="{{ body_class|default('default', boolean=false) }}">
    {% block content %}{% endblock %}
    {% block script %}{% endblock %}
</body>
</html>

app/templates/update.html
{% extends 'base.html' %}

{% block title %}Update {{ field }} - SimpleBook{% endblock %}

{% block content %}
<form method="POST" action="{{ url_for('profile.update_submit', field=field) }}" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="block">
        <h2>Update</h2>

        {% include '_flash.html' %}

        <div class="fields">
            <div class="field">
                {{ form.old_password(placeholder=form.old_password.label.text) }}
            </div>
            <div class="field">
            {% if field == 'username' %}
                {{ form.username(placeholder=form.username.label.text) }}
            {% elif field == 'picture' %}
                {{ form.picture }}
            {% endif %}
            </div>

            <div class="field">
                {% set button_text, href, type = "Update", url_for('profile.update_submit', field=field), "button" %}
                {% include '_submit.html' %}
            </div>
        </div>

        <div class="links words">
            <a href="{{ url_for('profile.profile') }}">Go back</a>
        </div>
    </div>
</form>
{% endblock %}